version: "3"
services:
  devopsdb:
    image: dockersai891/bigproject:db
    ports:
      - "3306:3306"
  
    networks:
      - dbnetwork

  application:
    image: dockersai891/bigproject:myapp
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb

    networks:
      - dbnetwork

networks:
  dbnetwork:
    driver: overlay
